import { UserProfile, Post, Comment, ChatRoom, ChatMessage, PostAction, PostCategory } from './types'

export const USERS: Record<string, UserProfile> = {
  '1': {
    id: '1',
    nickname: '미련많은사람',
    gender: '여성',
    age: 27,
    daysSinceBreakup: 12,
    status: '차였음',
    chatStatus: '지금 대화 가능',
    bio: '오늘은 진짜 연락 안 하고 싶어요. 누가 좀 말려줘요.',
    showGender: true,
    showAge: true,
    allowMessages: true,
  },
  '2': {
    id: '2',
    nickname: '연락참는중',
    gender: '남성',
    age: 29,
    daysSinceBreakup: 3,
    status: '연락참는중',
    chatStatus: '천천히 답장',
    bio: '하루하루가 너무 길어요. 그냥 지나가길 기다려요.',
    showGender: true,
    showAge: true,
    allowMessages: true,
  },
  '3': {
    id: '3',
    nickname: '새벽감성',
    gender: '여성',
    age: 24,
    daysSinceBreakup: 45,
    status: '이별함',
    chatStatus: '지금 대화 가능',
    bio: '이제 좀 괜찮아질 수 있을까요. 이 감정이 언제 끝날지.',
    showGender: true,
    showAge: true,
    allowMessages: true,
  },
  '4': {
    id: '4',
    nickname: '잠틸거야',
    gender: '여성',
    age: 25,
    daysSinceBreakup: 6,
    status: '연락참는중',
    chatStatus: '지금 대화 가능',
    bio: '비슷한 상황인 사람 있으면 말 걸어줘요.',
    showGender: true,
    showAge: true,
    allowMessages: true,
  },
  '5': {
    id: '5',
    nickname: '재회가능할까',
    gender: '남성',
    age: 31,
    daysSinceBreakup: 27,
    status: '재회기다림',
    chatStatus: '천천히 답장',
    bio: '마지막 말이 아직도 귓가에 맴돌아요.',
    showGender: true,
    showAge: true,
    allowMessages: false,
  },
  '6': {
    id: '6',
    nickname: '포기말자',
    gender: '남성',
    age: 26,
    daysSinceBreakup: 14,
    status: '재회기다림',
    chatStatus: '지금 대화 가능',
    bio: '아직 포기 안 했어요.',
    showGender: true,
    showAge: true,
    allowMessages: true,
  },
}

export const POSTS: Post[] = [
  {
    id: '1',
    authorId: '1',
    category: '연락참기',
    title: '새벽마다 습관처럼 카톡 들어가게 돼',
    content: '3년을 만났는데 아직도 잘 안 믿겨.. 이유는 지금도 나한테 집중하고 싶어서.. 핑계 같아. 밥도 안 먹히고 계속 눈물만 나. 나만 이렇게 힘든 거야?\n\n다들 어떻게 버텼어? 시간 지나면 괜찮아지는 거 맞아? 지금은 아무것도 하기 싫고 아무도 만나기 싫어.',
    timeAgo: '16분 전',
    location: '서울',
    showDaysSinceBreakup: true,
    allowMessages: true,
    commentCount: 52,
    likeCount: 128,
    shareCount: 87,
  },
  {
    id: '2',
    authorId: '2',
    category: '연락참기',
    title: '지금 연락하면 후회할 거 알면서도..',
    content: '술 한잔만 마시면 바로 보내고 싶어짐 누가 좀 달려줘 ㅠㅠ',
    timeAgo: '1시간 전',
    location: '부산',
    showDaysSinceBreakup: true,
    allowMessages: true,
    commentCount: 36,
    likeCount: 94,
    shareCount: 61,
  },
  {
    id: '3',
    authorId: '5',
    category: '재회고민',
    title: '헤어진 지 한 달 됐는데',
    content: '서로 아직 좋아하는 게 느껴.. 근데 먼저 연락하기가 무서워 재회 가능성 있을까요?',
    timeAgo: '3시간 전',
    location: '경기',
    showDaysSinceBreakup: true,
    allowMessages: false,
    commentCount: 24,
    likeCount: 67,
    shareCount: 45,
  },
  {
    id: '4',
    authorId: '3',
    category: '이별했어요',
    title: '업데이트 보이면 아직도 심장 쿵 내려앉아',
    content: '안 보면 덜 아플까 싶어서 삭제했는데도 자꾸 생각나네. 근데 또 못 지우겠어. 어떻게 이 마음을 정리해야 할까.',
    timeAgo: '2시간 전',
    location: '인천',
    showDaysSinceBreakup: true,
    allowMessages: true,
    commentCount: 18,
    likeCount: 73,
    shareCount: 31,
  },
  {
    id: '5',
    authorId: '4',
    category: '위로받기',
    title: '지금은 너무 힘들지만 나중에 이 글 보면서 웃을 거야',
    content: '지금은 너무 힘들지만 나중에 이 글 보면서 웃을 거야 희망해. 여기 와서 글 쓰는 것만으로도 조금 나아지는 것 같아.',
    timeAgo: '4시간 전',
    location: '대구',
    showDaysSinceBreakup: true,
    allowMessages: true,
    commentCount: 41,
    likeCount: 156,
    shareCount: 89,
  },
  {
    id: '6',
    authorId: '6',
    category: '재회고민',
    title: '상대방이 먼저 차고 나서 연락 오면 어떻게 해야 하나요',
    content: '헤어지자고 한 사람이 갑자기 연락이 왔어요. 보고 싶다고. 어떻게 해야 할지 모르겠어요.',
    timeAgo: '5시간 전',
    location: '서울',
    showDaysSinceBreakup: true,
    allowMessages: true,
    commentCount: 33,
    likeCount: 88,
    shareCount: 52,
  },
]

export function getPostDetailActions(category: PostCategory): PostAction[] {
  if (category === '연락참기') {
    return [
      { type: 'empathy', label: '공감해요', count: 128 },
      { type: 'noSend', label: '보내지마', count: 87 },
      { type: 'hug', label: '안아주기', count: 42 },
    ]
  }
  if (category === '재회고민') {
    return [
      { type: 'empathy', label: '공감해요', count: 67 },
      { type: 'noSend', label: '응원해요', count: 45 },
      { type: 'hug', label: '안아주기', count: 23 },
    ]
  }
  return [
    { type: 'empathy', label: '공감해요', count: 73 },
    { type: 'noSend', label: '보내지마', count: 31 },
    { type: 'hug', label: '안아주기', count: 18 },
  ]
}

export const CATEGORY_COLORS: Record<string, string> = {
  '이별했어요': 'bg-charcoal-100 text-charcoal-600',
  '연락참기': 'bg-charcoal-100 text-charcoal-700',
  '재회고민': 'bg-charcoal-100 text-charcoal-600',
  '위로받기': 'bg-charcoal-100 text-charcoal-500',
  '대화친구': 'bg-charcoal-100 text-charcoal-400',
}

export const COMMENTS: Comment[] = [
  {
    id: '1',
    postId: '1',
    authorId: '3',
    content: '너만 힘든 거 아니야. 나도 똑같이 시간은 진짜 약이야 조금만 버텨보자',
    timeAgo: '10분 전',
    likeCount: 23,
    location: '인천',
  },
  {
    id: '2',
    postId: '1',
    authorId: '4',
    content: '지금은 너무 힘들겠지만 나중에 이 글 보면서 웃을 수 있는 날이 올 거야 힘내!',
    timeAgo: '20분 전',
    likeCount: 18,
    location: '대구',
  },
  {
    id: '3',
    postId: '1',
    authorId: '6',
    content: '저도 그 마음 알아요. 오늘 밤은 같이 버텨요.',
    timeAgo: '32분 전',
    likeCount: 5,
    location: '서울',
  },
  {
    id: '4',
    postId: '2',
    authorId: '1',
    content: '연락하지마요. 지금 이 새벽이 제일 위험해요. 핸드폰 잠깐 내려놓아요.',
    timeAgo: '5분 전',
    likeCount: 31,
    location: '서울',
  },
  {
    id: '5',
    postId: '2',
    authorId: '3',
    content: '저도 어제 참았어요. 같이 버텨요.',
    timeAgo: '12분 전',
    likeCount: 14,
    location: '인천',
  },
  {
    id: '6',
    postId: '3',
    authorId: '4',
    content: '27일이면 많이 참으신 거예요. 서두르지 않아도 될 것 같아요.',
    timeAgo: '1시간 전',
    likeCount: 9,
    location: '대구',
  },
]

export const CHAT_ROOMS: ChatRoom[] = [
  {
    id: '4',
    participantId: '4',
    lastMessage: '오늘은 연락 안 하고 잘 넘겼어요?',
    lastMessageAt: '오후 11:32',
    unreadCount: 2,
  },
  {
    id: '3',
    participantId: '3',
    lastMessage: '감사해요. 덕분에 조금 나아졌어요 :)',
    lastMessageAt: '오후 9:14',
    unreadCount: 0,
  },
  {
    id: '1',
    participantId: '1',
    lastMessage: '맞아요 저도 그랬어요. 결국 참았어요.',
    lastMessageAt: '어제',
    unreadCount: 1,
  },
]

export const CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  '4': [
    { id: '1', senderId: '4', content: '안녕하세요. 글 보고 연락드렸어요.', timeAgo: '어제 11:20' },
    { id: '2', senderId: 'me', content: '안녕하세요. 비슷한 상황인 것 같아서요.', timeAgo: '어제 11:22' },
    { id: '3', senderId: '4', content: '이별 며칠째예요?', timeAgo: '어제 11:24' },
    { id: '4', senderId: 'me', content: '저는 6일째예요. 너무 힘들어요.', timeAgo: '어제 11:25' },
    { id: '5', senderId: '4', content: '저도 비슷해요. 같이 버텨봐요.', timeAgo: '오후 10:15' },
    { id: '6', senderId: '4', content: '오늘은 연락 안 하고 잘 넘겼어요?', timeAgo: '오후 11:32' },
  ],
  '3': [
    { id: '1', senderId: 'me', content: '글 보고 마음이 너무 아파서요.', timeAgo: '어제 9:00' },
    { id: '2', senderId: '3', content: '따뜻하게 봐줘서 감사해요.', timeAgo: '어제 9:05' },
    { id: '3', senderId: 'me', content: '괜찮아질 거예요. 진짜로요.', timeAgo: '오후 9:10' },
    { id: '4', senderId: '3', content: '감사해요. 덕분에 조금 나아졌어요 :)', timeAgo: '오후 9:14' },
  ],
  '1': [
    { id: '1', senderId: '1', content: '쪽지 받아주셔서 감사해요.', timeAgo: '어제 8:00' },
    { id: '2', senderId: 'me', content: '힘들겠다 생각이 들어서요.', timeAgo: '어제 8:05' },
    { id: '3', senderId: '1', content: '맞아요 저도 그랬어요. 결국 참았어요.', timeAgo: '어제 8:10' },
  ],
}

export const CONSOLATION_POSTS = POSTS.filter(p => ['4', '5'].includes(p.id))
